<?php
$messages = $this->messages;
if (empty ( $messages )) {
	return '';
}
if (! is_array ( $messages ) && ! $messages instanceof Traversable) {
	return;
}

// Flatten message array
$messagesToPrint = array();
$self = $this;
array_walk_recursive ( $messages, function ($item) use(&$messagesToPrint, $escapeHtml, $self) {
	$item = $this->translate ( $item );
	$messagesToPrint [] = $self->escapehtml ( $item );
} );

foreach ( $messagesToPrint as $msg ) {
	?>
<div class="alert alert-danger" role="alert">
	<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
	<span class="sr-only">Error:</span><?php echo $msg; ?>
</div>

<?php
}

?>